export const headerColumn = [
  {
    field: "col1",
    headerName: "نام فرش",
    width: 180,
    headerClassName: "super-app-theme--header",
    headerAlign: "center",
  },
  {
    field: "col2",
    type: "number",
    headerName: "قیمت",
    width: 150,
    headerClassName: "super-app-theme--header",
    headerAlign: "center",
  },
  {
    field: "col3",
    headerName: "تخفیف",
    type: "number",
    width: 100,
    headerClassName: "super-app-theme--header",
    headerAlign: "center",
  },
  {
    field: "col4",
    headerName: "قیمت نهایی",
    type: "number",
    width: 100,
    headerClassName: "super-app-theme--header",
    headerAlign: "center",
  },
  {
    field: "col5",
    headerName: "موجودی انبار",
    type: "number",
    width: 100,
    headerClassName: "super-app-theme--header",
    headerAlign: "center",
  },
  {
    field: "col6",
    headerName: "تاریخ ثبت کالا",
    type: "date",
    width: 180,
    headerClassName: "super-app-theme--header",
    headerAlign: "center",
  },
  {
    field: "col7",
    headerName: "عملیات",
    width: 150,
    headerClassName: "super-app-theme--header",
    headerAlign: "center",
  },
];
